function add_legend()
xlabel('Time')
legend('Joint 1 Pos',...
    'Joint 2 Pos',...
    'Joint 3 Pos',...
    'Joint 4 Pos',...
    'Joint 5 Pos',...
    'Joint 6 Pos',...
    'Joint 7 Pos',...
    'Location','northwest');

end