controller_list:
  - name: fake_arm_controller
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
      - joint_a7
  - name: fake_end_effector_controller
    joints:
      - dummy_ee_joint