# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

# Safety joint velocity limit should be 0.872665
joint_limits:
  dummy_ee_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1.0
  joint_a1:
    has_velocity_limits: true
    max_velocity: 0.7895
    has_acceleration_limits: true
    max_acceleration: 0.355275
  joint_a2:
    has_velocity_limits: true
    max_velocity: 0.7895
    has_acceleration_limits: true
    max_acceleration: 0.355275
  joint_a3:
    has_velocity_limits: true
    max_velocity: 0.9730
    has_acceleration_limits: true
    max_acceleration: 0.43785
  joint_a4:
    has_velocity_limits: true
    max_velocity: 1.2162
    has_acceleration_limits: true
    max_acceleration: 0.54729
  joint_a5:
    has_velocity_limits: true
    max_velocity: 1.7143
    has_acceleration_limits: true
    max_acceleration: 0.771435
  joint_a6:
    has_velocity_limits: true
    max_velocity: 2.6471
    has_acceleration_limits: true
    max_acceleration: 1.1912
  joint_a7:
    has_velocity_limits: true
    max_velocity: 3.3962
    has_acceleration_limits: true
    max_acceleration: 1.52829
